# SPDX-License: CC-BY-SA-4.0

# I used Dr. Yoav Ben-Dov's book "The Marseille Tarot Revealed" (2015) for reference.
# All words in this file are my own.

[alt_text.major_arcana]

00 = "A village fool is being chased by a dog scratching at his exposed buttocks while he wanders aimlessly in nature carrying a rod on his shoulder with a sack on the end."
01 = "A fancifully dressed street magician in the middle of a performance stands in front of a table displaying conjouring tools. He holds a wand in one hand."
02 = "A wise woman, begarbed in flowing religious regalia, holds open a large tome."
03 = "An empress seated on a throne holds an orbed scepter bearing a cross in one hand, while caressing a shield bearing the image of a heraldic eagle with the other."
04 = "An empreror leans against a throne while holding an orbed scepter bearing a cross. A shield bearing the image of a heraldic eagle rests against the throne."
05 = "A crowned holy man stands between two stone columns with his right hand in a gesture of benediction while his left hand holds a triple cross. Unclear shapes of figures in the foreground are reminisencent of people receiving counsel."
06 = "A young man stands between two attentive young women while a suspended naked cupid aims an arrow at the youth caught in the middle."
07 = "An armored and decorated man carrying a spear travels triumphantly in a horse-drawn carriage with a draped canopy."
08 = "A regal figure faces us seated on a throne with measuring scales in one hand and a long-sword in the other."
09 = "An aging man in monastic robes with unkempt hair hunches forward with a walking stick and a lantern."
10 = "A large mechanical wooden wheel rotates while strange creatures with both animal and human parts climb its scaffolding and platforms."
11 = "A woman, wearing a a colorful dress and large hat, tames a lion."
12 = "A man is suspended upside-down from a wooden frame with his hands behind his back and his legs crossed into a T-shape."
13 = "A skeleton drags a golden scythe through a field littered with bones, severed heads and budding plants."
14 = "A winged angelic woman transfers water between two golden chalices, the water hanging suspended over a dreamy landscape."
15 = "A winged demon with an exposed penis and breasts presides over two lesser imps chained together in bondage."
16 = "Two people plummet from a tall brick tower toward the natural landscape of a river flowing through grassy hills."
17 = "A naked woman pours water from two golden calices into a pond beneath a star-filled sky."
18 = "The moon presides high in the sky above two canine-like animals with their tongues out while a clawed aquatic creature resides in a large pool of water."
19 = "Two children engage playfully under an anthropomorphic sun."
20 = "A winged angel emerges from the clouds blowing a horn. Naked and surreal bodies rise to attention."
21 = "A naked woman draped in a thin cloth and surrounded by a wreath of feathers floats in the heavens. Floating alongside her appear divine beings, both human and animal."

[alt_text.minor_arcana.pentacles]
ace = "A single coin inscribed with a four-petal flower in the center lays flat on a surface, with plants growing above and below the coin."



[alt_text.minor_arcana.cups]
ace = "An ornate golden chalice, whose top is reminisencent moreso of the jagged foritfications of a city wall rather than a smooth drinking surface, emerges from a water-covered surface."
