[deck]
id = "ascii-tarot"
name = "ASCII Tarot"
version = "1.0"
author = "Kathryn Isabelle Lawrence"
license = "MIT"
schema_version = "1.0"
url = "https://github.com/lawreka/ascii-tarot"
description = "Minimal ASCII tarot deck taken from the ascii-tarot npm package by lawreka"
