#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
#
# SPDX-FileCopyrightText: 2026 Adam Fidel
# SPDX-License-Identifier: MIT
"""Render the release notes for a deck.

release_notes.py <deck>            print the generated block to stdout
release_notes.py <deck> --apply    splice the block into the live release body
release_notes.py <deck> --check    fail if the live body has drifted
release_notes.py --all [...]       every deck that has a release tag
"""

from __future__ import annotations

import argparse
import html
import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path
from urllib.parse import quote

REPO_ROOT = Path(__file__).resolve().parent.parent
FALLBACK_REPO = "arcanaland/reference-decks"
SPEC_URL = "https://github.com/arcanaland/specifications"

BEGIN = "<!-- BEGIN generated by tools/release_notes.py -->"
END = "<!-- END generated by tools/release_notes.py -->"

# Cards per row in the major arcana grid.
GRID_COLUMNS = 6
# Rendered width of each grid thumbnail, in pixels.
THUMB_WIDTH = 110

SGR = re.compile(r"\x1b\[[0-9;]*m")

# Used when a deck ships no names/en.toml of its own.
DEFAULT_MAJOR_NAMES = [
    "The Fool",
    "The Magician",
    "The High Priestess",
    "The Empress",
    "The Emperor",
    "The Hierophant",
    "The Lovers",
    "The Chariot",
    "Strength",
    "The Hermit",
    "Wheel of Fortune",
    "Justice",
    "The Hanged Man",
    "Death",
    "Temperance",
    "The Devil",
    "The Tower",
    "The Star",
    "The Moon",
    "The Sun",
    "Judgement",
    "The World",
]

# Cards previewed as text art when a deck has no raster images.
ART_PREVIEW = ["00", "21"]


def run(*args: str, ok: bool = False) -> str:
    """Run a command in the repo and return its stdout."""
    proc = subprocess.run(
        args, cwd=REPO_ROOT, capture_output=True, text=True, encoding="utf-8"
    )
    if proc.returncode != 0:
        if ok:
            return ""
        sys.exit(f"{args[0]}: {proc.stderr.strip() or proc.returncode}")
    return proc.stdout


def repo_slug() -> str:
    """owner/name of the origin remote."""
    url = run("git", "remote", "get-url", "origin", ok=True).strip()
    match = re.search(r"github\.com[:/](.+?)(?:\.git)?$", url)
    return match.group(1) if match else FALLBACK_REPO


class Tree:
    """The files of one deck, read from a tag or from the working tree."""

    def __init__(self, deck: str, ref: str | None):
        self.deck = deck
        self.ref = ref
        if ref:
            listing = run("git", "ls-tree", "-r", "--name-only", ref, "--", f"{deck}/")
            self.paths = sorted(p for p in listing.splitlines() if p)
        else:
            root = REPO_ROOT / deck
            self.paths = sorted(
                str(p.relative_to(REPO_ROOT))
                for p in root.rglob("*")
                if p.is_file() and ".git" not in p.parts
            )

    def read(self, path: str) -> str:
        if self.ref:
            return run("git", "show", f"{self.ref}:{path}")
        return (REPO_ROOT / path).read_text(encoding="utf-8")

    def has(self, path: str) -> bool:
        return path in self.paths

    def under(self, subdir: str) -> list[str]:
        prefix = f"{self.deck}/{subdir}/"
        return [p for p in self.paths if p.startswith(prefix)]

    def variants(self) -> list[str]:
        """Top-level directory names inside the deck, in listing order."""
        seen = []
        for path in self.paths:
            parts = path.split("/")
            if len(parts) > 2 and parts[1] not in seen:
                seen.append(parts[1])
        return seen


def tag_name(deck: str, version: str) -> str:
    return f"{deck}/v{version}"


def tag_exists(tag: str) -> bool:
    return bool(run("git", "rev-parse", "--verify", "--quiet", f"{tag}^{{}}", ok=True))


def load_deck(deck: str) -> tuple[dict, Tree, str]:
    """Return the [deck] table, the file tree, and the release tag."""
    # The version decides the tag, so it has to come from the working tree first.
    meta = tomllib.loads((REPO_ROOT / deck / "deck.toml").read_text())["deck"]
    tag = tag_name(deck, str(meta["version"]))
    if tag_exists(tag):
        tree = Tree(deck, tag)
        meta = tomllib.loads(tree.read(f"{deck}/deck.toml"))["deck"]
    else:
        print(f"note: {tag} is not a tag here, using the working tree", file=sys.stderr)
        tree = Tree(deck, None)
    return meta, tree, tag


def card_names(tree: Tree) -> dict[str, str]:
    """Major arcana names, keyed by the two-digit card id."""
    path = f"{tree.deck}/names/en.toml"
    if tree.has(path):
        table = tomllib.loads(tree.read(path)).get("major_arcana", {})
        if table:
            return {str(k): v for k, v in table.items()}
    return {f"{i:02d}": name for i, name in enumerate(DEFAULT_MAJOR_NAMES)}


def raster_variant(tree: Tree) -> str | None:
    """The tallest hNNN directory."""
    heights = [
        (int(m.group(1)), v)
        for v in tree.variants()
        if (m := re.fullmatch(r"h(\d+)", v))
    ]
    return max(heights)[1] if heights else None


def art_variant(tree: Tree) -> str | None:
    widths = [
        (int(m.group(1)), v)
        for v in tree.variants()
        if (m := re.fullmatch(r"ansi(\d+)", v))
    ]
    return max(widths)[1] if widths else None


def raw_url(repo: str, tag: str, path: str) -> str:
    ref = quote(f"refs/tags/{tag}", safe="/")
    return f"https://raw.githubusercontent.com/{repo}/{ref}/{quote(path, safe='/')}"


def major_grid(tree: Tree, repo: str, tag: str, variant: str) -> str:
    """An HTML table of the 22 majors. Markdown has no way to lay this out."""
    names = card_names(tree)
    cards = sorted(tree.under(f"{variant}/major_arcana"))
    rows = []
    for start in range(0, len(cards), GRID_COLUMNS):
        cells = []
        for path in cards[start : start + GRID_COLUMNS]:
            card_id = Path(path).stem
            name = html.escape(names.get(card_id, card_id))
            src = raw_url(repo, tag, path)
            cells.append(
                f'<td align="center" width="{THUMB_WIDTH}">'
                f'<img width="{THUMB_WIDTH}" alt="{name}" src="{src}">'
                f"<br><sub>{name}</sub></td>"
            )
        rows.append("  <tr>" + "".join(cells) + "</tr>")
    return "<table>\n" + "\n".join(rows) + "\n</table>"


def art_preview(tree: Tree, variant: str) -> str:
    """Text decks get a couple of cards inline instead of a grid."""
    names = card_names(tree)
    blocks = []
    for card_id in ART_PREVIEW:
        matches = [
            p
            for p in tree.under(f"{variant}/major_arcana")
            if Path(p).stem == card_id
        ]
        if not matches:
            continue
        art = SGR.sub("", tree.read(matches[0])).rstrip("\n")
        name = names.get(card_id, card_id)
        blocks.append(f"**{name}**\n\n```\n{art}\n```")
    return "\n\n".join(blocks)


def describe(variant: str, count: int) -> str | None:
    if variant == "scalable":
        return f"`scalable/` | Vector (SVG) | {count}"
    if m := re.fullmatch(r"h(\d+)", variant):
        return f"`{variant}/` | Raster, {m.group(1)}px tall | {count}"
    if m := re.fullmatch(r"ansi(\d+)", variant):
        return f"`{variant}/` | Text art, {m.group(1)} lines tall | {count}"
    if variant == "card_backs":
        return f"`card_backs/` | Card backs | {count}"
    return None


def contents(tree: Tree) -> str:
    lines = ["| Directory | Kind | Files |", "| --- | --- | --- |"]
    for variant in tree.variants():
        row = describe(variant, len(tree.under(variant)))
        if row:
            lines.append(f"| {row} |")
    locales = sorted(Path(p).stem for p in tree.under("names"))
    if locales:
        lines.append("")
        lines.append(f"Localized card names: {', '.join(f'`{l}`' for l in locales)}.")
    return "\n".join(lines)


def licensing(meta: dict, tree: Tree, repo: str, tag: str) -> str:
    lines = [f"- **License:** `{meta['license']}`"]
    if copyright_ := meta.get("copyright"):
        lines.append(f"- **Copyright:** {copyright_}")
    if attribution := meta.get("attribution"):
        lines.append(f"- **Attribution:** {attribution}")
    if author := meta.get("author"):
        lines.append(f"- **Artist:** {author}")
    if website := meta.get("website"):
        lines.append(f"- **Website:** {website}")

    ref = quote(f"refs/tags/{tag}", safe="/")
    for name in meta.get("license_files", []):
        path = f"{tree.deck}/{name}"
        if tree.has(path):
            url = f"https://github.com/{repo}/blob/{ref}/{quote(path, safe='/')}"
            lines.append(f"- **License text:** [`{path}`]({url})")
    return "\n".join(lines)


def render(deck: str) -> tuple[str, str]:
    """Return the generated block and the release tag it belongs to."""
    meta, tree, tag = load_deck(deck)
    repo = repo_slug()

    parts = [BEGIN, "", meta["description"], ""]

    raster = raster_variant(tree)
    art = art_variant(tree)
    if raster:
        parts += ["## Major Arcana", "", major_grid(tree, repo, tag, raster), ""]
    elif art:
        parts += ["## Major Arcana", "", art_preview(tree, art), ""]

    backs = tree.under("card_backs")
    if backs and raster:
        src = raw_url(repo, tag, sorted(backs)[0])
        parts += [
            "## Card Back",
            "",
            f'<img width="{THUMB_WIDTH}" alt="Card back" src="{src}">',
            "",
        ]

    parts += ["## Contents", "", contents(tree), ""]
    parts += ["## License and Attribution", "", licensing(meta, tree, repo, tag), ""]
    parts += [
        f"Packaged per the [Tarot Deck Specification]({SPEC_URL}), "
        f"schema version {meta['schema_version']}.",
        "",
        END,
    ]
    return "\n".join(parts), tag


def splice(body: str, block: str) -> str:
    """Replace the generated block, keeping anything written by hand around it."""
    start, end = body.find(BEGIN), body.find(END)
    if start != -1 and end != -1:
        return body[:start] + block + body[end + len(END) :]
    if not body.strip():
        return block + "\n"
    return body.rstrip() + "\n\n" + block + "\n"


def live_body(tag: str) -> str:
    out = run("gh", "release", "view", tag, "--json", "body")
    return json.loads(out)["body"].replace("\r\n", "\n")


def decks() -> list[str]:
    return sorted(
        p.parent.name
        for p in REPO_ROOT.glob("*/deck.toml")
        if not p.parent.name.startswith(".")
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("deck", nargs="?", help="deck directory, e.g. aquatic-tarot")
    parser.add_argument("--all", action="store_true", help="every deck")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--apply", action="store_true", help="edit the live release")
    mode.add_argument("--check", action="store_true", help="fail on drift")
    args = parser.parse_args()

    if args.all == bool(args.deck):
        parser.error("give a deck name or --all, not both")

    targets = decks() if args.all else [args.deck]
    for deck in targets:
        if not (REPO_ROOT / deck / "deck.toml").is_file():
            sys.exit(f"{deck}: no deck.toml")

    drifted = []
    for deck in targets:
        block, tag = render(deck)

        if not (args.apply or args.check):
            if len(targets) > 1:
                print(f"===== {tag} =====")
            print(block)
            continue

        if not tag_exists(tag):
            print(f"{tag}: no such tag, skipping", file=sys.stderr)
            continue

        current = live_body(tag)
        wanted = splice(current, block)
        if current == wanted:
            print(f"{tag}: up to date")
        elif args.check:
            print(f"{tag}: release notes have drifted")
            drifted.append(tag)
        else:
            subprocess.run(
                ["gh", "release", "edit", tag, "--notes-file", "-"],
                cwd=REPO_ROOT,
                input=wanted,
                text=True,
                check=True,
                stdout=subprocess.DEVNULL,
            )
            print(f"{tag}: updated")

    return 1 if drifted else 0


if __name__ == "__main__":
    sys.exit(main())
