name: Package and Release Tarot Deck

on:
  # Manual trigger
  workflow_dispatch:
  # Run on push to main branch with tag
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        run: |
          mkdir -p .github/workflows/scripts
          chmod +x .github/workflows/scripts/extract-version.sh
          chmod +x .github/workflows/scripts/create-package.sh

      - name: Extract version
        id: version
        run: |
          VERSION=$(.github/workflows/scripts/extract-version.sh)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get current time
        id: current_time
        run: |
          echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Create package
        id: create_package
        run: |
          # Create the package and capture only the filename
          FILENAME=$(.github/workflows/scripts/create-package.sh "${{ steps.version.outputs.version }}" "${{ steps.current_time.outputs.timestamp }}")
          
          # Debug output
          echo "Package script returned: '$FILENAME'"
          
          # Validate that the file exists
          if [ -f "$FILENAME" ]; then
            echo "Found package file: $FILENAME"
            echo "package_path=$FILENAME" >> $GITHUB_OUTPUT
          else
            echo "ERROR: Package file not found: $FILENAME"
            exit 1
          fi

      - name: Debug outputs
        run: |
          echo "Version: ${{ steps.version.outputs.version }}"
          echo "Package path: ${{ steps.create_package.outputs.package_path }}"
          ls -la

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        # Run this step in all cases where we have a package
        if: steps.create_package.outputs.package_path != ''
        with:
          files: ${{ steps.create_package.outputs.package_path }}
          name: Rider-Waite-Smith Tarot Deck v${{ steps.version.outputs.version }}
          tag_name: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || format('v{0}', steps.version.outputs.version) }}
          draft: false
          prerelease: false
          body: |
            Rider-Waite-Smith Tarot Deck v${{ steps.version.outputs.version }}
            
            This release contains the packaged Rider-Waite-Smith tarot deck according to the Tarot Deck Specification.
            
            **Package Information:**
            - Version: ${{ steps.version.outputs.version }}
            - Build Date: ${{ steps.current_time.outputs.timestamp }}
            - Created by: ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

